#!/usr/bin/env bash
# Installs HAProxy

apt-get update
apt-get install -y haproxy

printf %s "
frontend hbnb-lb_front
        bind *:80
        mode http
        default_backend hbnb-lb_back
backend hbnb-lb_back
        balance roundrobin
        server 2547-web-01 44.211.117.243 check
        server 2547-web-02 18.232.119.90 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
