#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 2547-web-01 44.211.117.243 check
        server 2547-web-02 18.232.119.90 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
